#!/bin/sh /etc/rc.common

USE_PROCD=1
START=97
STOP=03

start_service() {
	[ -x /usr/libexec/warp-watchdog ] || return 1

	procd_open_instance watchdog
	procd_set_param command /usr/libexec/warp-watchdog
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param term_timeout 5
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger warp
}
