#!/bin/sh /etc/rc.common

USE_PROCD=1
START=97
STOP=03

start_service() {
	[ -x /usr/libexec/warp-watchdog ] || return 1
	[ ! -e /etc/warp/disabled ] || return 0
	[ -s /etc/warp/awg-account.json ] || return 0
	[ -s /etc/warp/awg.conf ] || return 0
	config_load warp
	config_get backend main actual_backend ''
	[ "$backend" = amneziawg ] || return 0

	procd_open_instance watchdog
	procd_set_param command /usr/libexec/warp-watchdog
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param term_timeout 5
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger warp
}
